export default {
    WASHER_VIEW_CHARTS: "/washers/viewchart",
    WASHER_COMPLETED: "/bookings/completed",
    PAYMENTS: "/owners/makestripepayment",
    ASSIGNED_WASHER: "/washers/assignedwalks/:credential_id",
    HISTORY: "/history",
    DOGS: "/dogs",
    OWNER_PROFILE: "/ownerprofile",
    NEW_LISTINGS: "/newlistings",
    LISTINGS_DETAIL: "/listings/detail/",
    LISTING_DETAIL_BY_ID: "/listings/detail/:bookingId",
    ABOUT: "/about",
    PROFILE_WASHER: "/profile/washer/",
    PROFILE_OWNER: "/profile/owner/",
    EDIT_PROFILE_WASHER: "/profile/washer/edit",
    EDIT_PROFILE_OWNER: "/profile/owner/edit",
    WASHERS: "/washers",
    WASHER: "/washers/:credentialId",
    OWNERS: "/owners",
    OWNER: "/owners/:credentialId",
    DASHBOARD_WASHER: "/dashboard/washer",
    DASHBOARD_OWNER: "/dashboard/owner",
    LOGIN: "/login",
    SIGNUP: "/signup",

    HOME: "/",
    NOT_FOUND: "/notfound",
    CREATE_BOOKINGS_OWNER: "/bookings/create",
    CALENDAR: "/calendar",
    SOCIAL: "/social",
    SUCCESSFUL_PAYMENT: "/successful_payment",
    UNSUCCESSFUL_PAYMENT: "/unsuccessful_payment",
    STRIPE_SIGNUP: "/stripesignup",
};
